[book]
authors = ["tlannigan"]
language = "en"
multilingual = false
src = "src"
title = "Modded Minecraft Guide"

[output.html]
git-repository-url = "https://github.com/tlannigan/modded-minecraft-guide"